export const lithologyElements = [
    { id: "loam", name: "Loam" },
    { id: "sandy-loam", name: "Sandy Loam" },
    { id: "clay", name: "Clay" },
    { id: "sandy-gravel", name: "Sandy Gravel" },
    { id: "pebble-and-gravel", name: "Pebble and Gravel" },
    { id: "pebbly", name: "Pebbly" },
    { id: "boulder-pebble", name: "Boulder-Pebble" },
    { id: "sand", name: "Sand" },
    { id: "gravel-with-gravel-and-sand", name: "Gravel with Gravel and Sand" },
    { id: "sand-with-gravel", name: "Sand with Gravel" },
    { id: "loam-with-clay", name: "Loam with Clay" },
    { id: "loamy-sand", name: "Loamy Sand" },
    { id: "gravel-with-sand-and-pebbles", name: "Gravel with Sand and Pebbles" },
    { id: "loam-with-gravel", name: "Loam with Gravel" },
    { id: "clay-with-gravel", name: "Clay with Gravel" },
    { id: "gravel-with-pebbles", name: "Gravel with Pebbles" },
    { id: "pebbles-with-boulders-included", name: "Pebbles with Boulders Included" },
    { id: "conglomerate", name: "Conglomerate" },
    { id: "coarse-gravel", name: "Coarse Gravel" },
    { id: "sandy-loam-2", name: "Sandy Loam" },
    { id: "sand-with-sandy-loam-and-clay", name: "Sand with Sandy Loam and Clay" },
    { id: "sand-with-gravel-and-loam", name: "Sand with Gravel and Loam" },
    { id: "loam-with-sandy-loam", name: "Loam with Sandy Loam" },
    { id: "sand-with-sandy-loam", name: "Sand with Sandy Loam" },
    { id: "loam-with-pebbles", name: "Loam with Pebbles" },
    { id: "limestone-with-gypsum-interlayer", name: "Limestone with Gypsum Interlayer" },
    { id: "sand-with-loam-and-clay", name: "Sand with Loam and Clay" },
    { id: "sandstone-with-siltstone", name: "Sandstone with Siltstone" },
    { id: "sandstone", name: "Sandstone" },
    { id: "siltstone", name: "Siltstone" },
    { id: "limestone", name: "Limestone" },
    { id: "gravel", name: "Gravel" },
];