"""Lithology added

Revision ID: 35b1ec7e3b90
Revises: fd355398e0c6
Create Date: 2025-02-16 23:40:14.551300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b1ec7e3b90'
down_revision: Union[str, None] = 'fd355398e0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lithology',
    sa.Column('well', sa.Integer(), nullable=False),
    sa.Column('lithology', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['well'], ['geo_well.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lithology')
    # ### end Alembic commands ###
