"""Added melio

Revision ID: fd355398e0c6
Revises: bc4193fb2254
Create Date: 2025-02-15 15:54:52.936219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd355398e0c6'
down_revision: Union[str, None] = 'bc4193fb2254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('melio_organization',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melio_parametername',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melio_station',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melio_welltype',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melio_well',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('well_type', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.id'], ),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['organization'], ['melio_organization.id'], ),
    sa.ForeignKeyConstraint(['region'], ['region.id'], ),
    sa.ForeignKeyConstraint(['station'], ['melio_station.id'], ),
    sa.ForeignKeyConstraint(['well_type'], ['melio_welltype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('melio_parameter',
    sa.Column('well', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_name'], ['melio_parametername.id'], ),
    sa.ForeignKeyConstraint(['well'], ['melio_well.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('melio_parameter')
    op.drop_table('melio_well')
    op.drop_table('melio_welltype')
    op.drop_table('melio_station')
    op.drop_table('melio_parametername')
    op.drop_table('melio_organization')
    # ### end Alembic commands ###
