name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}           # Your server's IP or domain name
          username: ${{ secrets.USERNAME }}   # The SSH username
          key: ${{ secrets.SSH_KEY }}         # The private SSH key for authentication
          port: ${{ secrets.PORT }}           # SSH port (usually 22)
          script: |
            cd /home/xensa/hydrologic-database-fullstack
            git pull
            docker compose up --build -d
